title: Alys Murray
description: Welcome to my website

url: http://alysmurray.me/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Books
   url: /books
 - title: About
   url: /about
 - title: Contact
   url: /contact


social:
   twitter: alysmurr
   facebook: alys.murray
   email: hello@alysmurray.me

google_analytics: "UA-100893981-1"
